DROP TABLE IF EXISTS `env`;
CREATE TABLE `env` (
  `id` BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `env` VARCHAR(50) NOT NULL COMMENT '环境',
  `host_inner_ip`  VARCHAR(50) NOT NULL COMMENT 'HOST 内网 IP',
  `host_outer_ip`  VARCHAR(50) NOT NULL DEFAULT ' ' COMMENT 'HOST 外网 IP',
  `mysql_inner_ip` VARCHAR(50) NOT NULL DEFAULT ' ' COMMENT 'MYSQL 内网 IP',
  `mysql_outer_ip` VARCHAR(50) NOT NULL COMMENT 'MYSQL 外网 IP',
  `mysql_port`     VARCHAR(50) NOT NULL COMMENT 'MYSQL PORT'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `host`;
CREATE TABLE IF NOT EXISTS `host` (
  `id`          SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `host`        VARCHAR(63) NOT NULL DEFAULT ' ' COMMENT 'request_host＋端口',
  `host_name`   VARCHAR(255) COMMENT '所属项目/端',
  `description` VARCHAR(255) COMMENT '简述'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `uri`;
CREATE TABLE IF NOT EXISTS `uri` (
  `id`      BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `host_id` SMALLINT UNSIGNED NOT NULL DEFAULT ' ' COMMENT 'host id',
  `uri`     VARCHAR(127) NOT NULL DEFAULT ' ' COMMENT 'suffix',
  `project` VARCHAR(31)  NOT NULL DEFAULT ' ' COMMENT '请求方法'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `headers`;
CREATE TABLE IF NOT EXISTS `headers` (
  `id`            BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `host_id`       SMALLINT UNSIGNED NOT NULL DEFAULT ' ' COMMENT 'host id',
  `uri_id`        VARCHAR(127) NOT NULL DEFAULT ' ' COMMENT 'uri id',
  `method`        VARCHAR(31) NOT NULL DEFAULT ' ' COMMENT '请求方法',
  `authorization` VARCHAR(31) COMMENT '存放staff id，针对CRM系统',
  `cookie`        VARCHAR(255) COMMENT 'cookie信息，WWW | H5 访问',
  `content_type`  VARCHAR(31) NOT NULL DEFAULT ' ' COMMENT 'application/json |text 等'
)DEFAULT CHARSET=utf8